apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alex
spec:
  rules:
  - host: alexbissessur.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: anubis-alex
            port:
              number: 3000
