apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: servfail-updater
    name: servfail-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servfail-updater
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: servfail-updater
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: registry.alexbissessur.dev/servfailupdate:latest
        name: servfailupdate
        resources: {}

        volumeMounts:
        - name: ipstore
          mountPath: /app/ipstore

      volumes:
      - name: ipstore
        persistentVolumeClaim:
          claimName: ipstore

status: {}
