# apiVersion: v1
# data:
#   init.sql: Q1JFQVRFIERBVEFCQVNFIElGIE5PVCBFWElTVFMgZ2hvc3RkYjsKCkNSRUFURSBVU0VSIElGIE5PVCBFWElTVFMgJ2dob3N0dXNlcidAJyUnIElERU5USUZJRUQgQlkgJ3Bhc3N3b3JkJzsKCkdSQU5UIEFMTCBQUklWSUxFR0VTIE9OIGdob3N0ZGIuKiBUTyAnZ2hvc3R1c2VyJ0AnJSc7CgpGTFVTSCBQUklWSUxFR0VTOwo=
# kind: Secret
# metadata:
#   creationTimestamp: null
#   name: mariadb-init-script-v1
