apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-reg-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: '21474836480'

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-auth-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
