ollama:
  models:
    pull:
      - "gemma3:1b"
      - "granite4:3b"
      - "granite4:1b-h"
      - "granite4:350m-h"
      # - "granite4:350m"

resources:
  limits:
    cpu: "1"
    memory: "6Gi"
  requests:
    cpu: "750m"
    memory: "2Gi"

persistentVolume:
  enabled: "true"
  size: 10Gi
