ollama:
  models:
    pull:
      - "gemma3:1b"
      - "granite4:1b-h"
      - "granite4:350m-h"
      - "granite4:350m"

resources:
  requests:
    memory: "3Gi"

persistentVolume:
  enabled: "true"
  size: 10Gi
