apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stump
spec:
  rules:
  - host: stump.alexbissessur.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stump
            port:
              number: 80
