apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: uwuroute
spec:
  entryPoints:
  - websecure
  - web
  routes:
  - kind: Rule
    match: Host(`matrix.nyanyamachine.dev`)
    services:
    - name: continuwuity-svc
      port: 6167
  tls:
    secretName: matrix-cert # certResolver: le
