grafana:
  # Use an existing secret for the admin user.
  admin:
    existingSecret: "grafana-password"
    userKey: admin-user
    passwordKey: admin-password

  ingress:
    annotations: {
      "kubernetes.io/ingress.class": "traefik",
      "ingress.kubernetes.io/force-ssl-redirect": "false",
      "ingress.kubernetes.io/ssl-redirect": "false",
      "traefik.ingress.kubernetes.io/router.tls": "false",
      "traefik.ingress.kubernetes.io/frontend-entry-points": web
    }

    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.alexbissessur.dev
    path: /
