apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: navidrome
  name: navidrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: navidrome
    spec:
      containers:
      - image: deluan/navidrome:0.58.0
        name: navidrome
        ports:
        - containerPort: 4533
        resources: {}
        volumeMounts:
          - name: navidrome-data
            mountPath: /data
          - name: navidrome-music
            mountPath: /music
          - name: navidrome-alex
            mountPath: /alex
          - name: navidrome-dool
            mountPath: /dool

    volumes:
      - name: navidrome-data
        persistentVolumeClaim:
          claimName: navidrome-data
      - name: navidrome-music
        persistentVolumeClaim:
          claimName: navidrome-music
      - name: navidrome-alex
        persistentVolumeClaim:
          claimName: navidrome-alex
      - name: navidrome-dool
        persistentVolumeClaim:
          claimName: navidrome-dool
status: {}
