apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: navidrome
  name: navidrome
spec:
  ports:
  - port: 4533
    protocol: TCP
    targetPort: 4533
  selector:
    app: navidrome
status:
  loadBalancer: {}
